### ISSUE TITLE
I tried the command below, and It occurs error 'No such file or directory: 'system.transfer.list'',Why?

### ISSUE THREAD

**Issue by jacky1234** [xpirt/sdat2img#31]
-> % ./sdat2img.py system.transfer.list '/Users/yangjianfei/Downloads/miui_PYXIS_V11.0.1.0.QFCCNXM_ed59cac77c_10.0/system.new.dat' system.img
sdat2img binary - version: 1.2

Traceback (most recent call last):
  File "./sdat2img.py", line 143, in <module>
    main(TRANSFER_LIST_FILE, NEW_DATA_FILE, OUTPUT_IMAGE_FILE)
  File "./sdat2img.py", line 68, in main
    version, new_blocks, commands = parse_transfer_list_file(TRANSFER_LIST_FILE)
  File "./sdat2img.py", line 35, in parse_transfer_list_file
    trans_list = open(TRANSFER_LIST_FILE, 'r')
IOError: [Errno 2] No such file or directory: 'system.transfer.list'

**Comment by ysc3839** [comment]
Because `system.transfer.list` is not in current working directory.
I guess this file is also in `/Users/yangjianfei/Downloads/miui_PYXIS_V11.0.1.0.QFCCNXM_ed59cac77c_10.0/`. And you need some basic command line knowledge to use this program.

**Comment by jacky1234** [comment]
Is this file create personally or what this come from? Thank you!

**Comment by jacky1234** [comment]
Thank you
